"""API / endpoint wordlist for the ``endpoint_scan`` tool.

The base list is derived from the project's original ``api_endpoint_scan.py``
(strong AI/LLM coverage: OpenAI-compatible, Ollama, HF TGI, vLLM, Triton,
TensorFlow Serving, MLflow, LangServe). It is augmented with high-value paths
from public wordlists — chrislockard/api_wordlist and danielmiessler/SecLists —
covering Spring Boot Actuator, springdoc/springfox api-docs, Swagger-UI
variants, GraphQL IDEs, .well-known (OIDC/OAuth/AI-plugin/MCP), admin/debug
consoles, source/secret exposure, and CMS REST roots.
"""

from __future__ import annotations

_BASE = [
    "/",
    "/api",
    "/api/",
    "/api/v1",
    "/api/v2",
    "/api/v3",
    "/v1",
    "/v2",
    "/v3",
    "/rest",
    "/api/rest",
    "/api/auth",
    "/api/auth/login",
    "/api/auth/logout",
    "/api/login",
    "/api/logout",
    "/api/token",
    "/api/identity",
    "/api/session",
    "/api/sessions",
    "/api/v1/auth",
    "/api/v2/auth",
    "/api/v1/account/oauth/token",
    "/api/v1/account/oauth/ticket",
    "/api/v1/account/user",
    "/api/v1/account/user/profile",
    "/api/v1/account/user/register",
    "/api/v1/account/user/verify",
    "/api/v1/account/users/password",
    "/api/user",
    "/api/users",
    "/api/profile",
    "/api/me",
    "/api/whoami",
    "/api/user/current",
    "/api/user/me",
    "/api/users/current",
    "/api/users/me",
    "/api/v1/me",
    "/api/v2/me",
    "/api/account",
    "/api/accounts",
    "/api/v1/account/accounts",
    "/api/v1/account/accounts/summaries",
    "/api/v1/account/permissions",
    "/api/v1/account/users",
    "/api/v1/account/users/summaries",
    "/billing",
    "/api/billing",
    "/api/v1/billing",
    "/v1/billing",
    "/api/cart",
    "/api/cart/create",
    "/api/catalog",
    "/api/v1/catalog/products",
    "/api/v1/catalog/filters",
    "/api/stores",
    "/api/subscriptions",
    "/api/orders",
    "/api/v1/order",
    "/api/v2/paymentform",
    "/api-doc",
    "/api-docs",
    "/api/docs",
    "/api/apidocs",
    "/api/swagger",
    "/api/swagger.json",
    "/api/swagger.yaml",
    "/api/swagger.yml",
    "/api/v1/swagger.json",
    "/api/v1/swagger.yaml",
    "/api/v2/swagger.json",
    "/api/v2/swagger.yaml",
    "/swagger",
    "/swagger/",
    "/swagger.json",
    "/swagger.yaml",
    "/swagger/v1/swagger.json",
    "/openapi.json",
    "/openapi.yaml",
    "/api/openapi.json",
    "/application.wadl",
    "/api/application.wadl",
    "/graphql",
    "/api/graphql",
    "/api/v1/graphql",
    "/status",
    "/api/status",
    "/api/status.json",
    "/api/server_status",
    "/api/health",
    "/api/v1/health",
    "/api/v2/health",
    "/health",
    "/healthz",
    "/ready",
    "/readiness",
    "/live",
    "/liveness",
    "/api/ping",
    "/api/check",
    "/api/config",
    "/api/config.json",
    "/api/info.json",
    "/api/init",
    "/metrics",
    "/api/metrics",
    "/v1/metrics",
    "/api/clients",
    "/api/customer",
    "/api/customers",
    "/api/consumers",
    "/api/contents",
    "/api/events",
    "/api/messages",
    "/api/notifications",
    "/api/pages",
    "/api/plugins",
    "/api/projects",
    "/api/search",
    "/api/settings",
    "/api/widgets",
    "/api/v1/events",
    "/api/v1/notifications",
    "/api/v1/posts",
    "/api/v2/events",
    "/api/v2/jobs",
    "/api/v2/pages",
    "/api/v2/tickets",
    "/services",
    "/routes",
    "/plugins",
    "/consumers",
    "/upstreams",
    "/targets",
    "/certificates",
    "/snis",
    "/ca_certificates",
    "/vaults",
    "/v1/models",
    "/v1/chat/completions",
    "/v1/completions",
    "/v1/embeddings",
    "/v1/images/generations",
    "/v1/audio/transcriptions",
    "/v1/audio/translations",
    "/v1/audio/speech",
    "/v1/files",
    "/v1/fine_tuning/jobs",
    "/v1/fine-tuning/jobs",
    "/v1/batches",
    "/v1/responses",
    "/v1/assistants",
    "/v1/threads",
    "/v1/vector_stores",
    "/models",
    "/model",
    "/models/list",
    "/models/status",
    "/chat",
    "/chat/completions",
    "/completion",
    "/completions",
    "/generate",
    "/predict",
    "/prediction",
    "/inference",
    "/infer",
    "/invoke",
    "/query",
    "/response",
    "/responses",
    "/embed",
    "/embedding",
    "/embeddings",
    "/vector",
    "/vectors",
    "/vectorize",
    "/index",
    "/indexes",
    "/search",
    "/semantic-search",
    "/similarity",
    "/retrieve",
    "/retrieval",
    "/rerank",
    "/rank",
    "/knowledge",
    "/knowledge-base",
    "/knowledgebase",
    "/kb",
    "/memory",
    "/documents",
    "/document",
    "/chunks",
    "/chunk",
    "/context",
    "/agent",
    "/agents",
    "/assistant",
    "/assistants",
    "/tool",
    "/tools",
    "/function",
    "/functions",
    "/workflow",
    "/workflows",
    "/execute",
    "/run",
    "/task",
    "/tasks",
    "/prompt",
    "/prompts",
    "/templates",
    "/template",
    "/upload",
    "/uploads",
    "/files",
    "/assets",
    "/train",
    "/training",
    "/training/jobs",
    "/fine-tunes",
    "/fine_tunes",
    "/fine-tuning",
    "/jobs",
    "/batch",
    "/batches",
    "/images",
    "/image",
    "/generate-image",
    "/render",
    "/diffusion",
    "/audio",
    "/speech",
    "/tts",
    "/stt",
    "/transcribe",
    "/transcription",
    "/translate",
    "/synthesize",
    "/version",
    "/info",
    "/api/version",
    "/api/tags",
    "/api/show",
    "/api/generate",
    "/api/chat",
    "/api/embed",
    "/api/embeddings",
    "/api/pull",
    "/api/push",
    "/api/create",
    "/api/delete",
    "/api/copy",
    "/api/ps",
    "/generate_stream",
    "/v2/models",
    "/v2/health/live",
    "/v2/health/ready",
    "/v2/repository/index",
    "/v1/models/default",
    "/v1/models/default:predict",
    "/v1/models/default:metadata",
    "/invocations",
    "/ping",
    "/stream",
    "/input_schema",
    "/output_schema",
    "/config_schema",
    "/docs",
    "/redoc",
]

_AUGMENT = [
    # --- Spring Boot Actuator (info-leak / RCE surface; often unauthenticated) ---
    "/actuator",
    "/actuator/health",
    "/actuator/info",
    "/actuator/env",
    "/actuator/beans",
    "/actuator/configprops",
    "/actuator/mappings",
    "/actuator/loggers",
    "/actuator/metrics",
    "/actuator/prometheus",
    "/actuator/httptrace",
    "/actuator/httpexchanges",
    "/actuator/threaddump",
    "/actuator/heapdump",
    "/actuator/scheduledtasks",
    "/actuator/sessions",
    "/actuator/shutdown",
    "/actuator/gateway/routes",
    "/actuator/jolokia",
    "/actuator/caches",
    "/actuator/conditions",
    "/actuator/startup",
    "/actuator/auditevents",
    "/api/actuator",
    "/api/actuator/env",
    "/api/actuator/health",
    # bare / management-prefixed variants (older Spring, other frameworks)
    "/env",
    "/beans",
    "/mappings",
    "/heapdump",
    "/threaddump",
    "/loggers",
    "/configprops",
    "/trace",
    "/httptrace",
    "/jolokia",
    "/prometheus",
    "/autoconfig",
    "/manage",
    "/management",
    "/management/health",
    "/management/env",
    "/management/info",
    "/management/beans",
    "/internal",
    "/internal/health",

    # --- OpenAPI / Swagger UI variants (springdoc / springfox) ---
    "/v2/api-docs",
    "/v3/api-docs",
    "/api/v3/api-docs",
    "/api-docs.json",
    "/openapi",
    "/openapi.yml",
    "/swagger-ui",
    "/swagger-ui.html",
    "/swagger-ui/index.html",
    "/swagger-resources",
    "/swagger-resources/configuration/ui",
    "/api/swagger-ui.html",

    # --- GraphQL IDEs / schema introspection surfaces ---
    "/graphiql",
    "/playground",
    "/altair",
    "/graphql/console",
    "/graphql-explorer",
    "/graphql/schema.json",
    "/___graphql",
    "/subscriptions",
    "/v1/graphql",
    "/console",

    # --- .well-known (auth/OIDC discovery + AI/MCP manifests) ---
    "/.well-known/openid-configuration",
    "/.well-known/oauth-authorization-server",
    "/.well-known/oauth-protected-resource",
    "/.well-known/jwks.json",
    "/.well-known/security.txt",
    "/.well-known/ai-plugin.json",
    "/.well-known/mcp.json",

    # --- AI plugin / MCP / model-server surfaces ---
    "/mcp",
    "/api/mcp",
    "/sse",
    "/messages",
    "/run/predict",
    "/api/predict",
    "/queue/join",
    "/v1/messages",
    "/v1/complete",
    "/v1/moderations",
    "/v1/rerank",
    "/api/v1/generate",
    "/api/v1/model",

    # --- Admin / debug consoles ---
    "/admin",
    "/administrator",
    "/admin/login",
    "/dashboard",
    "/debug",
    "/debug/pprof",
    "/debug/vars",
    "/server-status",
    "/server-info",

    # --- Source / secret exposure (high severity) ---
    "/.git/config",
    "/.git/HEAD",
    "/.env",
    "/.env.local",
    "/.env.production",
    "/config.json",
    "/.svn/entries",
    "/backup",
    "/backup.zip",
    "/phpinfo.php",

    # --- CMS / framework REST roots ---
    "/wp-json",
    "/wp-json/wp/v2/users",
    "/wp-json/wp/v2/posts",
    "/jsonws/invoke",
    "/api/jsonws/invoke",
    "/api/jolokia/read",
]


def _dedupe(paths: list[str]) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for p in paths:
        p = p.strip()
        if not p:
            continue
        p = p if p.startswith("/") else "/" + p
        if p not in seen:
            seen.add(p)
            out.append(p)
    return out


# Deduped, order-preserving default wordlist (base first, then augmentation).
API_ENDPOINTS: list[str] = _dedupe(_BASE + _AUGMENT)


def load_wordlist(path: str) -> list[str]:
    """Load a custom endpoint wordlist file: one path per line, blank lines and
    '#' comments ignored, normalized + deduped."""
    lines = []
    with open(path, "r", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if line and not line.startswith("#"):
                lines.append(line)
    return _dedupe(lines)
